const $=id=>document.getElementById(id);
const kw=w=>(w/1000).toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2})+' kW';
const chargingStatus=status=>['Preparing','Charging','SuspendedEV','SuspendedEVSE','Finishing'].includes(status);
const age=time=>{if(!time)return'Nog nooit';const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(time))/1000));return seconds<60?seconds+' sec geleden':seconds<3600?Math.floor(seconds/60)+' min geleden':Math.floor(seconds/3600)+' uur geleden';};
let settings=null,dirty=false,sending=false,debounce=null,currentState=null,selectedStation=null,detailTab='status';
let configurationStation=null,configurationRows=[],configurationUpdatedAt=null,configurationBusy=false;

async function post(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const s=await r.json();if(!r.ok)throw Error(s.error);return s;}
function route(){const parts=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean),base=parts[0]||'overview';selectedStation=base==='stations'&&parts[1]?decodeURIComponent(parts[1]):selectedStation;const page=base==='stations'&&parts[1]?'station-detail':['overview','stations','ems','recovery','devices','logs'].includes(base)?base:'overview';document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===(page==='station-detail'?'stations':page)));const titles={overview:['OPERATIONS','Dashboard'],stations:['ASSETS','Laadstations'],'station-detail':['LAADSTATION','Laadstationdetails'],ems:['ENERGIE','EMS lab'],recovery:['SERVICE','Herstelcentrum'],devices:['AUTOMATISERING','Apparaten'],logs:['DIAGNOSE','Loganalyse']};$('pageEyebrow').textContent=titles[page][0];$('pageTitle').textContent=titles[page][1];if(page==='station-detail')showDetailTab(detailTab);if(currentState)render(currentState);}
function showDetailTab(name){detailTab=name;document.querySelectorAll('[data-detail-tab]').forEach(b=>b.classList.toggle('active',b.dataset.detailTab===name));document.querySelectorAll('[data-detail-pane]').forEach(p=>p.classList.toggle('active',p.dataset.detailPane===name));}
window.addEventListener('hashchange',route);document.querySelectorAll('[data-detail-tab]').forEach(b=>b.addEventListener('click',()=>showDetailTab(b.dataset.detailTab)));

function sync(s){$('pv').value=s.pvW;for(let i=0;i<3;i++)$('home'+i).value=s.homeW[i];for(const id of ['phases','limitA','fuseA'])$(id).value=s[id];for(const id of ['connected','meterOk'])$(id).checked=s[id];}
function labels(){if(!settings)return;$('pvValue').textContent=kw(settings.pvW);for(let i=0;i<3;i++)$('home'+i+'Value').textContent=kw(settings.homeW[i]);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===settings.mode));}
function meterFrom(item){const groups=Array.isArray(item?.meterValues?.meterValue)?item.meterValues.meterValue:[],samples=groups.flatMap(g=>(g.sampledValue||[]).map(v=>({...v,timestamp:g.timestamp||item.meterValues?.time})));const find=m=>{const v=samples.filter(x=>(x.measurand||'Energy.Active.Import.Register')===m).at(-1);return v?{value:Number(v.value),unit:v.unit||''}:null;};return{energy:find('Energy.Active.Import.Register'),power:find('Power.Active.Import'),timestamp:groups.at(-1)?.timestamp||item?.meterValues?.time||null};}
function formatValue(v){return v?Number(v.value).toLocaleString('nl-NL',{maximumFractionDigits:3})+' '+v.unit:'Nog niet ontvangen';}
function statusClass(item){if(item.chargerConnected&&item.backendConnected&&item.status==='Available'&&(!item.errorCode||item.errorCode==='NoError'))return'ok';if(item.chargerConnected&&item.backendConnected&&chargingStatus(item.status))return'charging';return'bad';}

function renderFleet(s){const fleet=Array.isArray(s.charger?.fleet)?s.charger.fleet:[],online=fleet.filter(x=>x.chargerConnected&&x.backendConnected).length,charging=fleet.filter(x=>chargingStatus(x.status)||x.activeTransaction).length,issues=fleet.filter(x=>statusClass(x)==='bad').length;$('navStationCount').textContent=fleet.length;$('kpiStations').textContent=fleet.length;$('kpiOnline').textContent=online;$('kpiCharging').textContent=charging;$('kpiIssues').textContent=issues;$('overviewPlatform').textContent=issues?'Aandacht vereist':'Alle systemen operationeel';$('overviewPlatform').className=issues?'status-warn':'status-ok';$('overviewUpdated').textContent=new Date().toLocaleTimeString('nl-NL');
  $('overviewStations').replaceChildren(...(fleet.length?fleet.slice(0,6).map(item=>{const row=document.createElement('div');row.className='compact-station';row.innerHTML=`<a href="#/stations/${encodeURIComponent(item.id)}">${item.id}</a><span><i class="status-dot ${statusClass(item)}"></i>${item.chargerConnected?'Homebox online':'Homebox offline'}</span><span>${item.status||'Onbekend'}</span><small>${age(item.lastSeen)}</small><a href="#/stations/${encodeURIComponent(item.id)}">Bekijken →</a>`;return row;}):[Object.assign(document.createElement('p'),{textContent:'Nog geen laadstations aangemeld.'})]));
  renderStationTable(fleet);renderStationDetail(s,fleet);
}
function renderStationTable(fleet){const q=$('stationSearch').value.trim().toLowerCase(),filter=$('stationStatusFilter').value,rows=fleet.filter(item=>{const match=!q||item.id.toLowerCase().includes(q)||(item.boot?.vendor||'').toLowerCase().includes(q);const group=filter==='all'||filter==='online'&&statusClass(item)==='ok'||filter==='charging'&&statusClass(item)==='charging'||filter==='issue'&&statusClass(item)==='bad';return match&&group;});$('stationResultCount').textContent=rows.length+' '+(rows.length===1?'resultaat':'resultaten');$('stationRows').replaceChildren(...(rows.length?rows.map(item=>{const tr=document.createElement('tr');tr.tabIndex=0;tr.innerHTML=`<td><strong>${item.id}</strong><small>${item.boot?.vendor||'Ecotap'} ${item.boot?.model||''}</small></td><td><i class="status-dot ${item.chargerConnected&&item.backendConnected?'ok':''}"></i>${item.chargerConnected&&item.backendConnected?'Online':'Offline'}</td><td><i class="status-dot ${statusClass(item)}"></i>${item.status||'Onbekend'}</td><td>${age(item.lastSeen)}</td><td>${item.forwarded||0}</td><td><span class="route-cell">${item.upstream||'Niet ingesteld'}</span></td><td class="open-row">›</td>`;const open=()=>location.hash='#/stations/'+encodeURIComponent(item.id);tr.addEventListener('click',open);tr.addEventListener('keydown',e=>{if(e.key==='Enter')open();});return tr;}):[(()=>{const tr=document.createElement('tr');tr.innerHTML='<td colspan="7">Geen laadstations gevonden.</td>';return tr;})()]));}
function selected(fleet){return fleet.find(x=>x.id===selectedStation)||fleet[0]||null;}
function renderConfiguration(){
  const q=$('configurationSearch').value.trim().toLowerCase(),rows=configurationRows.filter(row=>!q||row.key.toLowerCase().includes(q)||row.value.toLowerCase().includes(q));
  $('configurationCount').textContent=configurationRows.length?`${rows.length} van ${configurationRows.length} instellingen`:'Nog niet opgehaald';
  $('configurationRows').replaceChildren(...(rows.length?rows.map(row=>{const tr=document.createElement('tr'),key=document.createElement('td'),valueCell=document.createElement('td'),access=document.createElement('td'),action=document.createElement('td'),input=document.createElement('input'),pill=document.createElement('span'),save=document.createElement('button');key.textContent=row.key;input.className='configuration-value';input.value=row.value;input.disabled=row.readonly||configurationBusy;input.setAttribute('aria-label',`Waarde voor ${row.key}`);pill.className='access-pill'+(row.readonly?' readonly':'');pill.textContent=row.readonly?'Alleen lezen':'Wijzigbaar';save.className='save-config';save.textContent='Opslaan';save.disabled=true;input.addEventListener('input',()=>{save.disabled=configurationBusy||input.value===row.value;});save.addEventListener('click',()=>saveConfiguration(row,input,save));valueCell.append(input);access.append(pill);action.append(save);tr.append(key,valueCell,access,action);return tr;}):[(()=>{const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.textContent=configurationRows.length?'Geen instellingen gevonden.':'Klik op ‘Alles ophalen’ om GetConfiguration uit te voeren.';tr.append(td);return tr;})()]));
}
function mergeConfiguration(result,replace=false){const incoming=Array.isArray(result?.configurationKey)?result.configurationKey.map(row=>({key:String(row.key||''),readonly:!!row.readonly,value:String(row.value??'')})):[];if(replace)configurationRows=incoming;else for(const row of incoming){const current=configurationRows.find(item=>item.key===row.key);if(current)Object.assign(current,row);else configurationRows.push(row);}configurationRows.sort((a,b)=>a.key.localeCompare(b.key));configurationUpdatedAt=new Date().toISOString();renderConfiguration();return incoming;}
async function loadConfiguration(){if(!selectedStation||configurationBusy)return;configurationBusy=true;$('loadConfiguration').disabled=true;$('configurationResult').textContent='GetConfiguration wordt naar de laadcontroller gestuurd…';try{const response=await post('/api/fleet-command',{id:selectedStation,action:'getConfiguration'}),rows=mergeConfiguration(response.result,true);$('configurationResult').textContent=`${rows.length} instellingen ontvangen van ${selectedStation}.`;}catch(e){$('configurationResult').textContent=e.message;$('configurationResult').classList.add('error');setTimeout(()=>$('configurationResult').classList.remove('error'),2500);}finally{configurationBusy=false;$('loadConfiguration').disabled=false;renderConfiguration();}}
async function saveConfiguration(row,input,button){const next=input.value;if(next===row.value)return;if(!confirm(`${row.key} wijzigen van “${row.value}” naar “${next}”?`))return;configurationBusy=true;button.disabled=true;$('configurationResult').textContent=`ChangeConfiguration voor ${row.key} versturen…`;try{const changed=await post('/api/fleet-command',{id:selectedStation,action:'changeConfiguration',key:row.key,value:next});if(changed.result?.status!=='Accepted')throw Error(`Homebox antwoord: ${changed.result?.status||'onbekend'}`);const verified=await post('/api/fleet-command',{id:selectedStation,action:'getConfiguration',keys:[row.key]});mergeConfiguration(verified.result,false);$('configurationResult').textContent=`${row.key} is geaccepteerd en opnieuw uitgelezen. Actuele waarde: ${configurationRows.find(item=>item.key===row.key)?.value??next}`;}catch(e){input.value=row.value;$('configurationResult').textContent=e.message;$('configurationResult').classList.add('error');setTimeout(()=>$('configurationResult').classList.remove('error'),2500);}finally{configurationBusy=false;renderConfiguration();}}
function renderStationDetail(s,fleet){const item=selected(fleet);if(!item)return;selectedStation=item.id;$('detailStationId').textContent=item.id;$('detailStationMeta').textContent=(item.boot?.vendor||'Ecotap')+' · '+(item.boot?.model||'Laadcontroller')+' · laatste bericht '+age(item.lastSeen);const badge=$('detailStatusBadge');badge.textContent=item.status||'Onbekend';badge.className='status-badge '+statusClass(item);$('detailHomebox').textContent=item.chargerConnected?'Verbonden':'Offline';$('detailHomebox').className=item.chargerConnected?'status-ok':'status-bad';$('detailBackend').textContent=item.backendConnected?'Verbonden':'Offline';$('detailBackend').className=item.backendConnected?'status-ok':'status-bad';$('detailConnector').textContent=item.status||'Onbekend';$('detailError').textContent=item.errorCode||'NoError';$('detailError').className=!item.errorCode||item.errorCode==='NoError'?'status-ok':'status-bad';$('detailVendor').textContent=item.boot?.vendor||'Onbekend';$('detailFirmware').textContent=item.boot?.firmware||'Onbekend';
  const m=meterFrom(item);$('meterEnergy').textContent=formatValue(m.energy);$('meterPower').textContent=formatValue(m.power);$('connectionTraffic').textContent=(item.forwarded||0)+' doorgestuurd';$('connectionIdentity').textContent=item.id;$('meterFreshness').textContent=m.timestamp?'Laatste meting: '+new Date(m.timestamp).toLocaleString('nl-NL')+' · via de proxy doorgestuurd':'Nog geen MeterValues gezien sinds de laatste start.';$('meterHistory').textContent=item.meterHistory?.length?item.meterHistory.map(x=>new Date(x.time).toLocaleString('nl-NL')+' · '+formatValue(x.energy)+' · '+formatValue(x.voltageL1)+' · '+formatValue(x.currentL1)).join('\n'):'Nog geen opgeslagen metingen.';$('connectionEvents').textContent=item.events?.length?item.events.map(e=>new Date(e.time).toLocaleTimeString('nl-NL')+' · '+e.action+(e.detail?' · '+e.detail:'')).join('\n'):'Nog geen OCPP-berichten ontvangen.';$('proxyRouteStatus').textContent='Actief: '+(item.upstream||'niet ingesteld');if(document.activeElement!==$('proxyRoute'))$('proxyRoute').value=item.upstream||'';$('connectionEndpoint').textContent='Proxyverbinding voor '+item.id;$('connectionError').textContent=item.error||'';
  document.querySelectorAll('[data-fleet-service]').forEach(b=>{const disruptive=['softReset','hardReset','unlock','operative','inoperative','clearCache','clearProfile','remoteStart'].includes(b.dataset.fleetService);b.disabled=!item.chargerConnected||(disruptive&&(item.activeTransaction||chargingStatus(item.status)))||(b.dataset.fleetService==='remoteStop'&&!item.transactionId);});
  $('loadConfiguration').disabled=!item.chargerConnected||configurationBusy;if(configurationStation!==item.id){configurationStation=item.id;configurationRows=Array.isArray(item.configuration)?structuredClone(item.configuration):[];configurationUpdatedAt=item.configurationUpdatedAt||null;renderConfiguration();}else if(!configurationBusy&&item.configurationUpdatedAt&&item.configurationUpdatedAt!==configurationUpdatedAt&&document.activeElement?.closest?.('[data-detail-pane="configuration"]')===null){configurationRows=structuredClone(item.configuration||[]);configurationUpdatedAt=item.configurationUpdatedAt;renderConfiguration();}
  renderDiagnostics(s,item);
  if(item.id===s.charger.id)renderIntelligence(s);else{$('qualityScore').textContent=item.chargerConnected&&item.backendConnected?'90/100 · Sterk':'25/100 · Kritiek';$('dropoutRisk').textContent=item.chargerConnected&&item.backendConnected?'5%':'90%';$('latencyP95').textContent='Nog meten';$('connectionFlaps').textContent='—';$('intelligenceFindings').textContent=item.error||'Geen storingssignaal in de actuele verbinding.';}
}

function renderDiagnostics(s,item){const report=s.diagnostics?.[item.id]||null,button=$('requestDiagnostics'),status=$('diagnosticsStatus'),identity=$('meterIdentity'),configuredSetting=item.configuration?.find(row=>row.key==='chg_KWH1')?.value||null,configuredType=configuredSetting?.split(',')[0]||null;button.disabled=!item.chargerConnected;if(!report){status.textContent=item.chargerConnected?'Klaar om een diagnosebestand op te vragen.':'Homebox is offline; GetDiagnostics kan niet worden afgeleverd.';status.className='health-banner warning';identity.textContent=configuredType?'Ingesteld volgens controller: '+configuredType+'. Fysiek metermodel nog niet bevestigd.':'Fysiek metermodel nog niet gecontroleerd.';identity.className='health-banner warning';return;}const controllerStatus=item.diagnosticsStatus||report.controllerStatus;status.textContent=report.status+(controllerStatus?' · controller: '+controllerStatus:'')+(report.error?' · '+report.error:'');status.className='health-banner '+(report.status==='Ontvangen'?'':report.status==='Mislukt'||/fail/i.test(controllerStatus||'')?'critical':'warning');const assessment=report.meterAssessment||null,values=[report.fileName||'Nog niet gemeld',report.bytes?Math.round(report.bytes/1024)+' kB':'—',report.receivedAt?new Date(report.receivedAt).toLocaleString('nl-NL'):'Wachten op upload',assessment?.configured||report.meterConfiguration?.type||configuredType||'Nog niet bepaald',assessment?.observed?.join(', ')||'Niet in bestand gemeld'];$('diagnosticsMeta').querySelectorAll('strong').forEach((node,index)=>node.textContent=values[index]);identity.textContent=assessment?assessment.label+' · '+assessment.detail:configuredType?'Ingesteld volgens controller: '+configuredType+'. Het fysieke model kan pas na ontvangst van het diagnosebestand worden bevestigd.':'Wachten op het diagnosebestand om ingesteld en waargenomen metermodel te vergelijken.';identity.className='health-banner '+(assessment?.level||'warning');const findings=report.analysis?.findings||[];$('diagnosticsFindings').replaceChildren(...(findings.length?findings.map(item=>{const row=document.createElement('div');row.className='finding '+item.level;const title=document.createElement('b'),detail=document.createElement('span');title.textContent=item.title+' · '+item.evidence;detail.textContent=item.action;row.append(title,detail);return row;}):[Object.assign(document.createElement('div'),{className:'finding',textContent:'Wachten tot de Homebox het diagnosebestand heeft geüpload.'})]));$('diagnosticsExcerpt').textContent=report.excerpt||'Nog geen bestand ontvangen.';}

function renderIntelligence(s){const i=s.intelligence;if(i){$('qualityScore').textContent=i.score+'/100 · '+i.grade;$('qualityScore').className=i.score>=85?'status-ok':i.score>=65?'status-warn':'status-bad';$('dropoutRisk').textContent=i.risk+'%';$('latencyP95').textContent=i.latencyP95Ms===null?'Nog meten':Math.round(i.latencyP95Ms)+' ms';$('connectionFlaps').textContent=i.disconnects15m;$('intelligenceFindings').replaceChildren(...i.findings.map(item=>{const row=document.createElement('div');row.className='finding '+item.level;row.innerHTML=`<b>${item.title}</b><span>${item.detail}</span>`;return row;}));}if(s.logAnalysis)$('logAnalysis').replaceChildren(...s.logAnalysis.findings.map(item=>{const row=document.createElement('div');row.className='finding '+item.level;row.innerHTML=`<b>${item.title} · ${item.evidence}</b><span>${item.action}</span>`;return row;}));}
function renderService(s){const h=s.service;if(!h)return;$('serviceSummary').textContent=h.summary;$('serviceSummary').className='health-banner '+h.severity;$('serviceAdvice').textContent=h.advice;$('serviceLayers').replaceChildren(...h.layers.map(x=>{const el=document.createElement('div');el.className='layer';el.innerHTML=`<b class="${x.ok?'status-ok':'status-bad'}">${x.ok?'✓':'×'} ${x.name}</b><span>${x.detail}</span>`;return el;}));if(s.powerRecovery)$('powerRecovery').textContent=s.powerRecovery.label+' · '+s.powerRecovery.advice;const active=h.activeTransaction||chargingStatus(s.charger?.status);document.querySelectorAll('[data-service]').forEach(b=>b.disabled=!s.charger?.chargerConnected||(active&&['softReset','unlock','clearProfile','operative'].includes(b.dataset.service)));$('smartRecovery').disabled=active;if(s.serviceResult)$('serviceResult').textContent=resultText(s.serviceResult);}
function resultText(v){return(v.status?v.status+'\n':'')+(v.steps?.join('\n')||JSON.stringify(v.result??v,null,2))+(v.advice?'\n'+v.advice:'');}
function render(s){currentState=s;const c=s.charger||{};$('incomingConnection').textContent=c.chargerConnected?'Verbonden':'Niet verbonden';$('incomingConnection').className=c.chargerConnected?'status-ok':'status-bad';$('backendConnection').textContent=c.backendConnected?'Verbonden':'Niet verbonden';$('backendConnection').className=c.backendConnected?'status-ok':'status-bad';renderFleet(s);renderService(s);if(!dirty&&!sending){settings=structuredClone(s.settings);sync(settings);labels();}const r=s.result;$('pvMetric').textContent=kw(s.settings.pvW);$('homeMetric').textContent=kw(s.settings.homeW.reduce((a,b)=>a+b,0));$('chargeMetric').textContent=kw(r.chargeW);$('amps').textContent=r.actualA.toFixed(1)+' A · '+s.settings.phases+' fase(n)';$('gridMetric').textContent=kw(Math.abs(r.gridW));$('gridDirection').textContent=r.gridW>=0?'Afname van het net':'Teruglevering';$('reason').textContent=r.reason;$('energy').textContent='Gesimuleerd geladen: '+(r.energyWh/1000).toLocaleString('nl-NL',{minimumFractionDigits:3,maximumFractionDigits:3})+' kWh';$('phaseValues').replaceChildren(...r.gridPhaseA.map((a,i)=>{const row=document.createElement('div');row.className='phase';row.innerHTML=`<span>L${i+1}</span><meter max="${s.settings.fuseA}" value="${Math.min(Math.abs(a),s.settings.fuseA)}"></meter><b>${a.toFixed(1)} A</b>`;return row;}));$('overload').textContent=r.overloaded?'Netlimiet op een fase overschreden.':'Negatief betekent teruglevering; de zwaarst belaste fase bepaalt de laadruimte.';draw(s.history);$('chargerLive').textContent='Homebox: '+(c.chargerConnected?'verbonden':'offline')+' · backend: '+(c.backendConnected?'verbonden':'offline')+' · '+(c.effectiveStatus||c.status||'Onbekend');if(s.led){$('ledLive').textContent=s.led.configured?'Led gekoppeld · '+(s.led.automatic?'automatisch · '+s.led.desiredColour:'handmatig'):'Led wacht op de Smart Life-koppeling';['ledGreen','ledRed','ledBlue','ledOff'].forEach(id=>$(id).disabled=!s.led.configured||s.led.busy);$('ledAuto').classList.toggle('active',s.led.automatic);}$('health').textContent='Live bijgewerkt om '+new Date().toLocaleTimeString('nl-NL');}
function draw(history){const svg=$('chart'),ns='http://www.w3.org/2000/svg';svg.replaceChildren();if(!history.length)return;const end=history.at(-1).time,start=end-120000,top=Math.max(6000,...history.map(p=>Math.max(p.pvW,p.chargeW)))*1.1,add=(tag,a,t)=>{const n=document.createElementNS(ns,tag);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));if(t)n.textContent=t;svg.append(n);};for(let i=0;i<4;i++){const y=15+i*48;add('line',{x1:48,x2:625,y1:y,y2:y,stroke:'#e3e9ef'});add('text',{x:0,y:y+4},(top*(1-i/3)/1000).toFixed(1)+' kW');}for(const[key,color]of[['pvW','#d3912d'],['chargeW','#2684c7']])add('polyline',{points:history.map(p=>(48+Math.max(0,(p.time-start)/120000)*577).toFixed(1)+','+(159-p[key]/top*144).toFixed(1)).join(' '),fill:'none',stroke:color,'stroke-width':3});}

function changed(){dirty=true;labels();clearTimeout(debounce);debounce=setTimeout(flush,180);}async function flush(){if(sending||!dirty)return;sending=true;dirty=false;try{render(await post('/api/settings',structuredClone(settings)));}finally{sending=false;if(dirty)flush();}}
['pv','home0','home1','home2'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='pv')settings.pvW=Number($(id).value);else settings.homeW[Number(id.at(-1))]=Number($(id).value);changed();}));['phases','limitA','fuseA'].forEach(id=>$(id).addEventListener('change',()=>{settings[id]=Number($(id).value);changed();}));['connected','meterOk'].forEach(id=>$(id).addEventListener('change',()=>{settings[id]=$(id).checked;changed();}));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{settings.mode=b.dataset.mode;changed();}));const presets={sun:{pvW:10000,homeW:[700,600,700]},cloud:{pvW:1500,homeW:[700,600,700]},cooking:{pvW:3000,homeW:[6500,700,800]},night:{pvW:0,homeW:[400,300,300]}};document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{Object.assign(settings,structuredClone(presets[b.dataset.preset]));sync(settings);changed();}));$('reset').addEventListener('click',async()=>render(await post('/api/reset',{})));
['ledGreen','ledRed','ledBlue','ledOff','ledAuto'].forEach(id=>$(id).addEventListener('click',()=>post('/api/led',{action:{ledGreen:'green',ledRed:'red',ledBlue:'blue',ledOff:'off',ledAuto:'auto'}[id]})));document.querySelectorAll('[data-status-sim]').forEach(b=>b.addEventListener('click',()=>post('/api/status-simulation',{status:b.dataset.statusSim})));
async function servicePost(url,data={},box=$('serviceResult')){box.textContent='Actie uitvoeren…';try{const v=await post(url,data);box.textContent=resultText(v.serviceResult||v.networkResult||v);}catch(e){box.textContent=e.message;box.classList.add('error');setTimeout(()=>box.classList.remove('error'),2500);}}
document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>servicePost('/api/service-command',{action:b.dataset.service})));$('networkDiagnostics').addEventListener('click',()=>servicePost('/api/network-diagnostics'));$('smartRecovery').addEventListener('click',()=>servicePost('/api/smart-recovery'));$('saveProxyRoute').addEventListener('click',()=>servicePost('/api/fleet-routing',{id:selectedStation,upstream:$('proxyRoute').value.trim()},$('stationActionResult')));$('resetProxyRoute').addEventListener('click',()=>{$('proxyRoute').value='ws://ocpp.robo-charge.net:80/'+selectedStation;});$('loadConfiguration').addEventListener('click',loadConfiguration);$('configurationSearch').addEventListener('input',renderConfiguration);$('requestDiagnostics').addEventListener('click',async()=>{const box=$('diagnosticsStatus');box.textContent='GetDiagnostics wordt naar '+selectedStation+' gestuurd…';box.className='health-banner warning';try{await post('/api/fleet-command',{id:selectedStation,action:'diagnostics'});box.textContent='Opdracht geaccepteerd. Wachten op de upload van de Homebox…';}catch(e){box.textContent=e.message;box.className='health-banner critical';}});const confirmations={softReset:'Soft reset uitvoeren op dit laadstation?',hardReset:'De laadcontroller volledig herstarten?',operative:'Connector beschikbaar maken?',inoperative:'Connector buiten gebruik zetten?',unlock:'Stekker op afstand ontgrendelen?',clearCache:'Lokale autorisatiecache wissen?',clearProfile:'Actief laadprofiel wissen?',remoteStart:'Een laadsessie starten met testtag LAADFIX?',remoteStop:'De actieve laadsessie stoppen?'};document.querySelectorAll('[data-fleet-service]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.fleetService;if(action==='configuration'){showDetailTab('configuration');loadConfiguration();return;}if(confirmations[action]&&!confirm(confirmations[action]))return;servicePost('/api/fleet-command',{id:selectedStation,action},$('stationActionResult'));}));
$('stationSearch').addEventListener('input',()=>currentState&&renderStationTable(currentState.charger?.fleet||[]));$('stationStatusFilter').addEventListener('change',()=>currentState&&renderStationTable(currentState.charger?.fleet||[]));$('logFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(f&&f.size<=250000){$('controllerLog').value=await f.text();$('logAnalysis').textContent=f.name+' geladen.';}});$('analyzeLog').addEventListener('click',async()=>{try{renderIntelligence(await post('/api/analyze-log',{log:$('controllerLog').value}));}catch(e){$('logAnalysis').textContent=e.message;}});
async function poll(){try{const r=await fetch('/api/state');if(!r.ok)throw Error();render(await r.json());}catch{$('health').textContent='Dashboard niet bereikbaar';$('health').className='error';}setTimeout(poll,1500);}route();poll();
